image: docker
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - export VERSION_MAJ_MIN_PAT=`sed -n "s|.*ver:\([0-9]\.[0-9]\.[0-9]\).*|\1|p" ver/latest.Dockerfile`
  - export VERSION_MAJ_MIN=`echo "${VERSION_MAJ_MIN_PAT:0:3}"`
  - export VERSION_MAJ=`echo "${VERSION_MAJ_MIN_PAT:0:1}"`

build-latest:
  stage: build
  script:
    - cd ver && docker build --pull -t $CI_REGISTRY_IMAGE:latest -f latest.Dockerfile .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$VERSION_MAJ_MIN_PAT
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$VERSION_MAJ_MIN
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$VERSION_MAJ
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$VERSION_MAJ_MIN_PAT
    - docker push $CI_REGISTRY_IMAGE:$VERSION_MAJ_MIN
    - docker push $CI_REGISTRY_IMAGE:$VERSION_MAJ
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - ver/latest.Dockerfile

build-version:
  stage: build
  script:
    - cd ver && docker build --pull -t $CI_REGISTRY_IMAGE:1.5.2 -f 1.5.2.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:1.5.2
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version"
      changes:
        - ver/1.5.2.Dockerfile
